name: run notebooks

# push or on schedule
on:
  push:
  schedule: 
    - cron:  '0 1 * * *'  # Every day at 1am 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  # This workflow contains a single job called "build"
  compute:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: 3.7

      - name: Install dependencies with conda # (the shell line is needed for conda paths etc)
        shell: bash -l {0}
        run: |
          conda env update -n base --file conda_packages.yml

      - name: Run the code
        shell: bash -l {0}
        run: |
          ./notebook_runner.sh

      
